services:
  vlmcsd-secure:
    build:
      context: .
      dockerfile: Dockerfile.secure
    image: vlmcsd:secure
    container_name: vlmcsd-hardened
    restart: unless-stopped
    
    # Network security
    ports:
      - "127.0.0.1:1688:1688"  # Bind only to localhost
    networks:
      - vlmcsd-internal
    
    # Security constraints
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.25'
        reservations:
          memory: 16M
          cpus: '0.1'
    
    # Capabilities and privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE  # Only needed if binding to privileged ports
    
    # Read-only root filesystem
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10M
      - /var/log/vlmcsd:noexec,nosuid,size=50M
    
    # No external volumes - using embedded config
    
    # Environment security
    environment:
      - MALLOC_ARENA_MAX=2  # Limit memory allocator arenas
    
    # Health check
    healthcheck:
      test: ["CMD", "/usr/bin/vlmcs", "-l", "3", "127.0.0.1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    
    # Logging with rotation
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=vlmcsd,security=hardened"

networks:
  vlmcsd-internal:
    driver: bridge
    internal: true  # No external access
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  vlmcsd-logs:
    driver: local